services:
  app:
    image: ghcr.io/keitogoto/gasuwari-nextjs:latest
    container_name: gasuwari-app
    restart: unless-stopped
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - LOG_DIR=/app/logs
    volumes:
      - gasuwari-logs:/app/logs
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

  watchtower:
    image: nickfedor/watchtower
    container_name: gasuwari-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable --cleanup --interval 60

volumes:
  gasuwari-logs: